/* eslint-disable unicorn/no-array-for-each */
/* eslint-disable sonarjs/cognitive-complexity */
/* eslint-disable security/detect-object-injection */
/* eslint-disable no-prototype-builtins */
/* eslint-disable unicorn/no-nested-ternary */

// To parse this data:
//
//   import { Convert } from '@/models/Organization';
//
//   const organization = Convert.toOrganization(json);
//
// These functions will throw an error if the JSON doesn't
// match the expected interface, even if the JSON is valid.

// Generated by https://quicktype.io

export interface IntegrationData {
  created: string;
  integration: string;
  end_user_organization_name: string;
  end_user_email_address: string;
  id: string;
  category: string;
  is_duplicate: boolean;
  end_user_origin_id: string;
  integration_slug: string;
  status: string;
  webhook_listener_url: string;
  account_id: string;
  account_token: string;
}

export interface Organization {
  id: string;
  name: string;
  email: string;
  admin_id: string;
  admin_email: string;
  user_list: string[];
  invited_user_list: string[];
  link_id_map: { [key: string]: IntegrationData };
  document_list: string[];
  created_at: string;
  updated_at: string;
}

// Converts JSON strings to/from your types
// and asserts the results of JSON.parse at runtime
export class Convert {
  public static toOrganization(json: any): Organization {
    return cast(json, r('Organization'));
  }

  public static OrganizationToJson(value: Organization): string {
    return JSON.stringify(uncast(value, r('Organization')), undefined, 2);
  }
}

function invalidValue(typ: any, value: any, key: any, parent: any = ''): never {
  const prettyTyp = prettyTypeName(typ);
  const parentText = parent ? ` on ${parent}` : '';
  const keyText = key ? ` for key "${key}"` : '';
  throw new Error(
    `Invalid value${keyText}${parentText}. Expected ${prettyTyp} but got ${JSON.stringify(
      value
    )}`
  );
}

function prettyTypeName(typ: any): string {
  if (Array.isArray(typ)) {
    return typ.length === 2 && typ[0] === undefined
      ? `an optional ${prettyTypeName(typ[1])}`
      : `one of [${typ
          .map(a => {
            return prettyTypeName(a);
          })
          .join(', ')}]`;
  } else if (typeof typ === 'object' && typ.literal !== undefined) {
    return typ.literal;
  } else {
    return typeof typ;
  }
}

function jsonToJSProperties(typ: any): any {
  if (typ.jsonToJS === undefined) {
    const map: any = {};
    typ.props.forEach((p: any) => (map[p.json] = { key: p.js, typ: p.typ }));
    typ.jsonToJS = map;
  }
  return typ.jsonToJS;
}

function jsToJSONProperties(typ: any): any {
  if (typ.jsToJSON === undefined) {
    const map: any = {};
    typ.props.forEach((p: any) => (map[p.js] = { key: p.json, typ: p.typ }));
    typ.jsToJSON = map;
  }
  return typ.jsToJSON;
}

function transform(
  value: any,
  typ: any,
  getProperties: any,
  key: any = '',
  parent: any = ''
): any {
  function transformPrimitive(typ: string, value_: any): any {
    if (typeof typ === typeof value_) return value_;
    return invalidValue(typ, value_, key, parent);
  }

  function transformUnion(typs: any[], value_: any): any {
    // val must validate against one typ in typs
    const l = typs.length;
    for (let index = 0; index < l; index++) {
      const typ = typs[index];
      try {
        return transform(value_, typ, getProperties);
      } catch (error) {
        console.log(error);
      }
    }
    return invalidValue(typs, value_, key, parent);
  }

  function transformEnum(cases: string[], value_: any): any {
    if (cases.includes(value_)) return value_;
    return invalidValue(
      cases.map(a => {
        return l(a);
      }),
      value_,
      key,
      parent
    );
  }

  function transformArray(typ: any, value_: any): any {
    // val must be an array with no invalid elements
    if (!Array.isArray(value_))
      return invalidValue(l('array'), value_, key, parent);
    return value_.map(element => transform(element, typ, getProperties));
  }

  function transformDate(value_: any): any {
    if (value_ === null) {
      return undefined;
    }
    const d = new Date(value_);
    if (Number.isNaN(d.valueOf())) {
      return invalidValue(l('Date'), value_, key, parent);
    }
    return d;
  }

  function transformObject(
    properties: { [k: string]: any },
    additional: any,
    value_: any
  ): any {
    if (
      value_ === null ||
      typeof value_ !== 'object' ||
      Array.isArray(value_)
    ) {
      return invalidValue(l(reference || 'object'), value_, key, parent);
    }
    const result: any = {};
    for (const key of Object.getOwnPropertyNames(properties)) {
      const property = properties[key];
      const v = Object.prototype.hasOwnProperty.call(value_, key)
        ? value_[key]
        : undefined;
      result[property.key] = transform(
        v,
        property.typ,
        getProperties,
        key,
        reference
      );
    }
    for (const key of Object.getOwnPropertyNames(value_)) {
      if (!Object.prototype.hasOwnProperty.call(properties, key)) {
        result[key] = transform(
          value_[key],
          additional,
          getProperties,
          key,
          reference
        );
      }
    }
    return result;
  }

  if (typ === 'any') return value;
  if (typ === null) {
    if (value === null) return value;
    return invalidValue(typ, value, key, parent);
  }
  if (typ === false) return invalidValue(typ, value, key, parent);
  let reference: any = undefined;
  while (typeof typ === 'object' && typ.ref !== undefined) {
    reference = typ.ref;
    typ = typeMap[typ.ref];
  }
  if (Array.isArray(typ)) return transformEnum(typ, value);
  if (typeof typ === 'object') {
    return typ.hasOwnProperty('unionMembers')
      ? transformUnion(typ.unionMembers, value)
      : typ.hasOwnProperty('arrayItems')
      ? transformArray(typ.arrayItems, value)
      : typ.hasOwnProperty('props')
      ? transformObject(getProperties(typ), typ.additional, value)
      : invalidValue(typ, value, key, parent);
  }
  // Numbers can be parsed by Date but shouldn't be.
  if (typ === Date && typeof value !== 'number') return transformDate(value);
  return transformPrimitive(typ, value);
}

function cast<T>(value: any, typ: any): T {
  return transform(value, typ, jsonToJSProperties);
}

function uncast<T>(value: T, typ: any): any {
  return transform(value, typ, jsToJSONProperties);
}

function l(typ: any) {
  return { literal: typ };
}

function a(typ: any) {
  return { arrayItems: typ };
}

function o(properties: any[], additional: any) {
  return { props: properties, additional };
}

function m(additional: any) {
  return { props: [], additional };
}

function r(name: string) {
  return { ref: name };
}

const typeMap: any = {
  Organization: o(
    [
      { json: 'id', js: 'id', typ: '' },
      { json: 'name', js: 'name', typ: '' },
      { json: 'email', js: 'email', typ: '' },
      { json: 'admin_id', js: 'admin_id', typ: '' },
      { json: 'admin_email', js: 'admin_email', typ: '' },
      { json: 'user_list', js: 'user_list', typ: a('') },
      { json: 'invited_user_list', js: 'invited_user_list', typ: a('') },
      { json: 'link_id_map', js: 'link_id_map', typ: m(r('IntegrationData')) },
      { json: 'document_list', js: 'document_list', typ: a('') },
      { json: 'created_at', js: 'created_at', typ: '' },
      { json: 'updated_at', js: 'updated_at', typ: '' },
    ],
    false
  ),
  IntegrationData: o(
    [
      { json: 'created', js: 'created', typ: '' },
      { json: 'integration', js: 'integration', typ: '' },
      {
        json: 'end_user_organization_name',
        js: 'end_user_organization_name',
        typ: '',
      },
      { json: 'end_user_email_address', js: 'end_user_email_address', typ: '' },
      { json: 'id', js: 'id', typ: '' },
      { json: 'category', js: 'category', typ: '' },
      { json: 'is_duplicate', js: 'is_duplicate', typ: true },
      { json: 'end_user_origin_id', js: 'end_user_origin_id', typ: '' },
      { json: 'integration_slug', js: 'integration_slug', typ: '' },
      { json: 'status', js: 'status', typ: '' },
      { json: 'webhook_listener_url', js: 'webhook_listener_url', typ: '' },
      { json: 'account_id', js: 'account_id', typ: '' },
      { json: 'account_token', js: 'account_token', typ: '' },
    ],
    false
  ),
};
